// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: edit.proto

package actionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EditArgs *EditArgs `protobuf:"bytes,1,opt,name=editArgs,proto3" json:"editArgs,omitempty"`
}

func (x *EditRequest) Reset() {
	*x = EditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRequest) ProtoMessage() {}

func (x *EditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_edit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRequest.ProtoReflect.Descriptor instead.
func (*EditRequest) Descriptor() ([]byte, []int) {
	return file_edit_proto_rawDescGZIP(), []int{0}
}

func (x *EditRequest) GetEditArgs() *EditArgs {
	if x != nil {
		return x.EditArgs
	}
	return nil
}

type EditArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mission          string   `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	Plan             string   `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Task             string   `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	FileIn           string   `protobuf:"bytes,4,opt,name=fileIn,proto3" json:"fileIn,omitempty"`
	FileOut          string   `protobuf:"bytes,5,opt,name=fileOut,proto3" json:"fileOut,omitempty"`
	Code             string   `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	InspirationFiles []string `protobuf:"bytes,7,rep,name=inspirationFiles,proto3" json:"inspirationFiles,omitempty"`
}

func (x *EditArgs) Reset() {
	*x = EditArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditArgs) ProtoMessage() {}

func (x *EditArgs) ProtoReflect() protoreflect.Message {
	mi := &file_edit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditArgs.ProtoReflect.Descriptor instead.
func (*EditArgs) Descriptor() ([]byte, []int) {
	return file_edit_proto_rawDescGZIP(), []int{1}
}

func (x *EditArgs) GetMission() string {
	if x != nil {
		return x.Mission
	}
	return ""
}

func (x *EditArgs) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *EditArgs) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *EditArgs) GetFileIn() string {
	if x != nil {
		return x.FileIn
	}
	return ""
}

func (x *EditArgs) GetFileOut() string {
	if x != nil {
		return x.FileOut
	}
	return ""
}

func (x *EditArgs) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *EditArgs) GetInspirationFiles() []string {
	if x != nil {
		return x.InspirationFiles
	}
	return nil
}

type EditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileWrites []*FileWrite `protobuf:"bytes,1,rep,name=fileWrites,proto3" json:"fileWrites,omitempty"`
}

func (x *EditResponse) Reset() {
	*x = EditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_edit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditResponse) ProtoMessage() {}

func (x *EditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_edit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditResponse.ProtoReflect.Descriptor instead.
func (*EditResponse) Descriptor() ([]byte, []int) {
	return file_edit_proto_rawDescGZIP(), []int{2}
}

func (x *EditResponse) GetFileWrites() []*FileWrite {
	if x != nil {
		return x.FileWrites
	}
	return nil
}

var File_edit_proto protoreflect.FileDescriptor

var file_edit_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x0b, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x65, 0x64, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62,
	0x2e, 0x45, 0x64, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x65, 0x64, 0x69, 0x74, 0x41,
	0x72, 0x67, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6c,
	0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x4f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x65, 0x4f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x10, 0x69, 0x6e, 0x73, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0x43, 0x0a, 0x0c, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x0a, 0x66,
	0x69, 0x6c, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x73, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_edit_proto_rawDescOnce sync.Once
	file_edit_proto_rawDescData = file_edit_proto_rawDesc
)

func file_edit_proto_rawDescGZIP() []byte {
	file_edit_proto_rawDescOnce.Do(func() {
		file_edit_proto_rawDescData = protoimpl.X.CompressGZIP(file_edit_proto_rawDescData)
	})
	return file_edit_proto_rawDescData
}

var file_edit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_edit_proto_goTypes = []interface{}{
	(*EditRequest)(nil),  // 0: actionpb.EditRequest
	(*EditArgs)(nil),     // 1: actionpb.EditArgs
	(*EditResponse)(nil), // 2: actionpb.EditResponse
	(*FileWrite)(nil),    // 3: actionpb.FileWrite
}
var file_edit_proto_depIdxs = []int32{
	1, // 0: actionpb.EditRequest.editArgs:type_name -> actionpb.EditArgs
	3, // 1: actionpb.EditResponse.fileWrites:type_name -> actionpb.FileWrite
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_edit_proto_init() }
func file_edit_proto_init() {
	if File_edit_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_edit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_edit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_edit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edit_proto_goTypes,
		DependencyIndexes: file_edit_proto_depIdxs,
		MessageInfos:      file_edit_proto_msgTypes,
	}.Build()
	File_edit_proto = out.File
	file_edit_proto_rawDesc = nil
	file_edit_proto_goTypes = nil
	file_edit_proto_depIdxs = nil
}
